name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r docs/source/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build -a docs/source/ _build
  
  # Deploy to the github-pages environment
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  
  # Specify runner + deployment step
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

